name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '20.19.4'
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Start Expo
      run: npx expo start --non-interactive &
    - name: Wait for Metro Bundler
      run: sleep 30
    - name: Check build
      run: curl --retry 3 --retry-delay 5 http://localhost:8081